import {
  getWsOrigin,
  type CertificateProbeResult,
  type TrustedCertificateEntry,
} from "../types/protocol";

export {
  appendInsecureLoopbackIfNeeded,
  isLoopbackHost,
  normalizeServerUrl,
  prepareServerUrl,
} from "./server-url";
import { formatInvokeError } from "./errors";

export async function probeServerCertificate(serverUrl: string): Promise<CertificateProbeResult> {
  const { invoke } = await import("@tauri-apps/api/core");
  try {
    return await invoke<CertificateProbeResult>("probe_server_certificate", { serverUrl });
  } catch (error) {
    throw new Error(formatInvokeError(error, "Zertifikat konnte nicht gelesen werden."));
  }
}

export async function saveTrustedCertificate(
  origin: string,
  entry: TrustedCertificateEntry,
): Promise<void> {
  const { invoke } = await import("@tauri-apps/api/core");
  await invoke("save_trusted_certificate", { origin, entry });
}

export async function saveTrustedCertificateForServer(
  serverUrl: string,
  entry: TrustedCertificateEntry,
): Promise<void> {
  const { invoke } = await import("@tauri-apps/api/core");
  await invoke("save_trusted_certificate_for_server", { serverUrl, entry });
}

export async function getPinnedFingerprint(serverUrl: string): Promise<string | null> {
  const { invoke } = await import("@tauri-apps/api/core");
  try {
    return await invoke<string | null>("get_pinned_fingerprint", { serverUrl });
  } catch {
    return null;
  }
}

export async function getPinnedFingerprintForHttpUrl(url: string): Promise<string | null> {
  const trimmed = url.trim();
  if (!trimmed) {
    return null;
  }

  const { invoke } = await import("@tauri-apps/api/core");
  try {
    return await invoke<string | null>("get_pinned_fingerprint_for_http_url", {
      assetUrl: trimmed,
    });
  } catch {
    return null;
  }
}

export function browserOrigin(url: string): string {
  return getWsOrigin(url);
}

/** Known consumer/enterprise TLS inspectors that re-sign HTTPS as a local MITM. */
const TLS_INTERCEPTION_PRODUCTS: ReadonlyArray<{ product: string; pattern: RegExp }> = [
  { product: "AVG", pattern: /\bavg\b/i },
  { product: "Avast", pattern: /\bavast\b/i },
  { product: "Kaspersky", pattern: /\bkaspersky\b/i },
  { product: "Bitdefender", pattern: /\bbitdefender\b/i },
  { product: "ESET", pattern: /\beset\b/i },
  { product: "Norton", pattern: /\bnorton\b/i },
  { product: "Symantec", pattern: /\bsymantec\b/i },
  { product: "McAfee", pattern: /\bmcafee\b/i },
  { product: "Trend Micro", pattern: /\btrend\s*micro\b/i },
  { product: "Sophos", pattern: /\bsophos\b/i },
  { product: "Fortinet", pattern: /\bfortinet\b|\bfortigate\b/i },
];

const GENERIC_TLS_INTERCEPTION_PATTERN =
  /web\s*\/?\s*mail\s*shield|web.?shield|https?\s*scan|ssl\s*inspection|https?\s*inspection|generated by .+ antivirus/i;

/**
 * Detects antivirus / HTTPS-scanning MITM from a certificate issuer DN.
 * Returns a short product label for UI copy, or null when no interceptor is recognized.
 */
export function detectAntivirusTlsInterception(issuer: string): string | null {
  const trimmed = issuer.trim();
  if (!trimmed) {
    return null;
  }

  for (const entry of TLS_INTERCEPTION_PRODUCTS) {
    if (entry.pattern.test(trimmed)) {
      return entry.product;
    }
  }

  if (GENERIC_TLS_INTERCEPTION_PATTERN.test(trimmed)) {
    return "Antivirus";
  }

  return null;
}
